# fly.toml app configuration file generated for lifestylebackend on 2023-11-16T21:56:49-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lifestylebackend"
primary_region = "sea"

[build]

[http_service]
  internal_port = 1300
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
