// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: deleteExpenses.sql

package db

import (
	"context"
)

const deleteSingleCapitalExpense = `-- name: DeleteSingleCapitalExpense :one
DELETE FROM capital_expenses
WHERE user_id = $1 AND capital_exp_id = $2
RETURNING budget_id, expenses
`

type DeleteSingleCapitalExpenseParams struct {
	UserID       int64 `json:"user_id"`
	CapitalExpID int64 `json:"capital_exp_id"`
}

type DeleteSingleCapitalExpenseRow struct {
	BudgetID int64  `json:"budget_id"`
	Expenses string `json:"expenses"`
}

func (q *Queries) DeleteSingleCapitalExpense(ctx context.Context, arg DeleteSingleCapitalExpenseParams) (DeleteSingleCapitalExpenseRow, error) {
	row := q.db.QueryRowContext(ctx, deleteSingleCapitalExpense, arg.UserID, arg.CapitalExpID)
	var i DeleteSingleCapitalExpenseRow
	err := row.Scan(&i.BudgetID, &i.Expenses)
	return i, err
}

const deleteSingleEatoutExpense = `-- name: DeleteSingleEatoutExpense :one
DELETE FROM eatout_expenses
WHERE user_id = $1 AND eatout_exp_id = $2
RETURNING budget_id, expenses
`

type DeleteSingleEatoutExpenseParams struct {
	UserID      int64 `json:"user_id"`
	EatoutExpID int64 `json:"eatout_exp_id"`
}

type DeleteSingleEatoutExpenseRow struct {
	BudgetID int64  `json:"budget_id"`
	Expenses string `json:"expenses"`
}

func (q *Queries) DeleteSingleEatoutExpense(ctx context.Context, arg DeleteSingleEatoutExpenseParams) (DeleteSingleEatoutExpenseRow, error) {
	row := q.db.QueryRowContext(ctx, deleteSingleEatoutExpense, arg.UserID, arg.EatoutExpID)
	var i DeleteSingleEatoutExpenseRow
	err := row.Scan(&i.BudgetID, &i.Expenses)
	return i, err
}

const deleteSingleEntertainmentExpense = `-- name: DeleteSingleEntertainmentExpense :one
DELETE FROM entertainment_expenses
WHERE user_id = $1 AND entertainment_exp_id = $2
RETURNING budget_id, expenses
`

type DeleteSingleEntertainmentExpenseParams struct {
	UserID             int64 `json:"user_id"`
	EntertainmentExpID int64 `json:"entertainment_exp_id"`
}

type DeleteSingleEntertainmentExpenseRow struct {
	BudgetID int64  `json:"budget_id"`
	Expenses string `json:"expenses"`
}

func (q *Queries) DeleteSingleEntertainmentExpense(ctx context.Context, arg DeleteSingleEntertainmentExpenseParams) (DeleteSingleEntertainmentExpenseRow, error) {
	row := q.db.QueryRowContext(ctx, deleteSingleEntertainmentExpense, arg.UserID, arg.EntertainmentExpID)
	var i DeleteSingleEntertainmentExpenseRow
	err := row.Scan(&i.BudgetID, &i.Expenses)
	return i, err
}
